package gui;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Profesor;


public class ExploracionAsignaciones extends javax.swing.JFrame {

    //preparacion de datos para pdfs
    ArrayList<Profesor> listaProf;
    DefaultTableModel dtm;
    private Font FUENTE_TITULOS = FontFactory.getFont(FontFactory.COURIER, 20, BaseColor.BLACK);
    private Font FUENTE_SUPERTITULOS = FontFactory.getFont(FontFactory.COURIER, 25, BaseColor.BLACK);
    private Font FUENTE_SUBTITULOS = FontFactory.getFont(FontFactory.COURIER, 16, BaseColor.BLACK);
    private Font FUENTE_TEXTO = FontFactory.getFont(FontFactory.COURIER, 12, BaseColor.BLACK);

    /**
     * Creates new form NewJFrame
     */
    public ExploracionAsignaciones() throws SQLException {
        initComponents();
        
        //estilo de botones
        jButton1.putClientProperty("JButton.buttonType", "roundRect");
        jButton2.putClientProperty("JButton.buttonType", "roundRect");
        jButton3.putClientProperty("JButton.buttonType", "roundRect");
        listaProf = crud.ProfesoresCRUD.leerTodos();
        logica.LogicaAsignaciones.fijarDatosAlExplorarAsignaciones("hey");
        dtm = (DefaultTableModel) jTable1.getModel();
        for (Profesor pro : listaProf) {
            jComboBox1.addItem(pro.getNombre() + " " + pro.getApellido());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exploración de asignaciones");
        setIconImage(new ImageIcon("src/main/resources/logo_programa.png").getImage());
        setMaximumSize(new java.awt.Dimension(900, 500));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancelar.png"))); // NOI18N
        jButton2.setText("Eliminar asignaciones");
        jButton2.setMaximumSize(new java.awt.Dimension(250, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(250, 40));
        jButton2.setPreferredSize(new java.awt.Dimension(250, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 7);
        jPanel3.add(jButton2, gridBagConstraints);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/documento.png"))); // NOI18N
        jButton3.setText("Informe simple");
        jButton3.setMaximumSize(new java.awt.Dimension(250, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(250, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(250, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 7);
        jPanel3.add(jButton3, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libro.png"))); // NOI18N
        jButton1.setText("Informe completo");
        jButton1.setMaximumSize(new java.awt.Dimension(250, 40));
        jButton1.setMinimumSize(new java.awt.Dimension(250, 40));
        jButton1.setPreferredSize(new java.awt.Dimension(250, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 7);
        jPanel3.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Profesor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Especialidad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("AAA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jPanel2.add(jComboBox1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Horas contratadas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Horas asignadas:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 2, 5);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 2, 5);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Módulos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 2, 5);
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 5, 2, 5);
        jPanel2.add(jLabel9, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Módulo", "Nombre", "Ciclo", "Tipo de ciclo", "Nivel", "Turno", "Curso", "Horas reales", "Horas ponde."
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        actualizarDatos();

    }//GEN-LAST:event_jComboBox1ActionPerformed

    //actualiza los datos ofrecidos
    private void actualizarDatos() {
        dtm.setRowCount(0);
        PreparedStatement st;
        try {
            st = logica.LogicaConexion.getConexion()
                    .prepareStatement(sql.Sentencias.getSELECCIONAR_ESPECIALIDAD());
            st.setString(1, String.valueOf(listaProf.get(jComboBox1.getSelectedIndex()).getIdEspecialidad()));
            ResultSet rs = st.executeQuery();
            rs.next();
            jLabel2.setText(rs.getString(2));
            st = logica.LogicaConexion.getConexion()
                    .prepareStatement(sql.Sentencias.getCONSEGUIR_ASIGNACIONES_POR_PROFESOR());
            st.setString(1, String.valueOf(listaProf.get(jComboBox1.getSelectedIndex()).getIdProfesor()));

            rs = st.executeQuery();
            boolean interruptor = false;
            while (rs.next()) {
                if (!interruptor) {
                    jLabel5.setText(String.valueOf(rs.getInt(11)));

                    interruptor = !interruptor;
                }
                dtm.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(8), rs.getString(9),
                    String.valueOf(rs.getInt(6)), rs.getString(7), rs.getString(5), String.valueOf(rs.getInt(3)),
                    String.valueOf(rs.getInt(4))});

            }

            int temporal = 0;
            for (int i = 0; i < dtm.getRowCount(); i++) {
                temporal += Integer.parseInt(dtm.getValueAt(i, 7).toString());
            }
            jLabel7.setText(String.valueOf(temporal));
            if (temporal > Integer.parseInt(jLabel5.getText())) {
                jLabel7.setForeground(Color.red);
            } else {
                jLabel7.setForeground(Color.green);
            }
            jLabel9.setText(String.valueOf(dtm.getRowCount()));
        } catch (SQLException ex) {
            Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Eliminar las asignaciones de módulos del profesor " + jComboBox1.getSelectedItem().toString() + "?") == 0) {
            try {
                PreparedStatement st = logica.LogicaConexion.getConexion().prepareStatement(sql.Sentencias.getBORRAR_ASIGNACIONES());
                st.setString(1, String.valueOf(listaProf.get(jComboBox1.getSelectedIndex()).getIdProfesor()));
                ResultSet rs = st.executeQuery();
                actualizarDatos();
            } catch (SQLException ex) {
                Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Profesor profTempo = listaProf.get(jComboBox1.getSelectedIndex());
            Document document = new Document(PageSize.A4.rotate()); //new Document(PageSize.A4.rotate())
            JFileChooser j = new JFileChooser();
            j.setFileSelectionMode(JFileChooser.FILES_ONLY);
            j.setSelectedFile(new File("Asignaciones " + profTempo.getNombre() + " " + profTempo.getApellido() + " (" + new SimpleDateFormat("yyyyMMddHHmmss").format(new Date()) + ").pdf"));
            if (j.showSaveDialog(this) == 0) {
                System.out.println(j.getSelectedFile());
                PdfWriter.getInstance(document, new FileOutputStream(j.getSelectedFile() + ".pdf"));
                document.open();
                logica.LogicaPDF.imprimirCabeceraDocumento(document);
                Paragraph titulo = new Paragraph("Informe de asignaciones de profesor\n", FUENTE_TITULOS);
                titulo.setAlignment(Element.ALIGN_CENTER);
                document.add(titulo);
                Paragraph profesor = new Paragraph(profTempo.getNombre() + " " + profTempo.getApellido(), FUENTE_SUPERTITULOS);
                profesor.setAlignment(Element.ALIGN_CENTER);
                document.add(profesor);
                
                        Paragraph especialidad = new Paragraph(jLabel2.getText() + "\n", FUENTE_SUBTITULOS);
                        especialidad.setAlignment(Element.ALIGN_CENTER);
                        document.add(especialidad);

                document.add(new Chunk("\n"));
                PdfPTable table = new PdfPTable(6);
                table.setWidths(new float[]{7, 31, 31, 5, 9, 8});
                logica.LogicaPDF.imprimirCabeceraTabla(table);

                logica.LogicaPDF.imprimirModulos(table, String.valueOf(profTempo.getIdProfesor()));
                document.add(table);
                document.close();
            }

        } catch (DocumentException ex) {
            Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //INFORME COMPLETO

        Document document = new Document(PageSize.A4.rotate()); //new Document(PageSize.A4.rotate())
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.FILES_ONLY);
        j.setSelectedFile(new File("Asignaciones de profesores" + " (" + new SimpleDateFormat("yyyyMMddHHmmss").format(new Date()) + ").pdf"));
        if (j.showSaveDialog(this) == 0) {
            try {
                System.out.println(j.getSelectedFile());
                PdfWriter.getInstance(document, new FileOutputStream(j.getSelectedFile() + ".pdf"));
                document.open();
                

                for (Profesor profe : listaProf) {
                    System.out.println(profe.toString());
                    if (logica.LogicaPDF.consultarSiTiene(profe.getIdProfesor()) > 0) {
                        logica.LogicaPDF.imprimirCabeceraDocumento(document);
                Paragraph titulo = new Paragraph("Informe de asignaciones de profesor\n", FUENTE_TITULOS);
                titulo.setAlignment(Element.ALIGN_CENTER);
                document.add(titulo);
                        Paragraph profesor = new Paragraph(profe.getNombre() + " " + profe.getApellido(), FUENTE_SUPERTITULOS);
                        profesor.setAlignment(Element.ALIGN_CENTER);
                        document.add(profesor);
                        Paragraph especialidad = new Paragraph(jLabel2.getText() + "\n\n", FUENTE_SUBTITULOS);
                        especialidad.setAlignment(Element.ALIGN_CENTER);
                        document.add(especialidad);
                document.add(new Chunk("\n"));
                        PdfPTable table = new PdfPTable(6);
                        table.setWidths(new float[]{7, 31, 31, 5, 9, 8});
                        logica.LogicaPDF.imprimirCabeceraTabla(table);

                        logica.LogicaPDF.imprimirModulos(table, String.valueOf(profe.getIdProfesor()));
                        document.add(table);
                        document.newPage();
                    }
                }

                document.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DocumentException ex) {
                Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExploracionAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExploracionAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExploracionAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExploracionAsignaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    ExploracionAsignaciones dialog = new ExploracionAsignaciones();
                    dialog.setVisible(true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ExploracionAsignaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
